version: "3.9"

services:
  lms-backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/lms-backend-db
      - JWT_SECRET=@th@rv@
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    restart: always

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
