services:
  - name: lms-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: "5000"
      - key: MONGODB_URI
        fromDatabase:
          name: lms_mongo
          property: connectionString
      - key: JWT_SECRET
        value: your_jwt_secret_here
    databases:
      - name: lms_mongo
        plan: free
        type: mongodb
